### ISSUE TITLE
PBL ISAM, PBL KEYFILE: Record/Page Locking, Multi-Threads, Multi-Users..

### ISSUE THREAD

**Issue by mladinox** [peterGraf/pbl#3]
Nice library, Peter, but the documentation don't mention anything about:
Record/Page Locking, Multi-Threading, or Multi-User use.

Is this library thread safe?

Can use PBL inside an Multi-User application, like multi-user server..?

Greetings, excellent library,
Thank you for this..

**Comment by peterGraf** [comment]
PBL is not thread safe. If you want to use it in a multi threaded application, thread safety has to be imposed on a level higher up.

I do not understand your question about multi-user, what would a datastructure library have to do with a multi-user application? Of course you can use PBL in a multi-user application, but PBL will not seperate the users for you.

**Comment by mladinox** [comment]
I mean about PBL-ISAM and PBL-KEYFILE, running embedded inside a network server application, sharing common ISAM/KEY files, serving requests from Multiple-Users.
In this context, the library could to offer Record/Page Locking and Multi-Threading, great improvement to reach, because using mutexes(because no thread safe) slows the performance.

**Comment by peterGraf** [comment]
PBL was not built for a multi-user scenario. It does not do record or page locking. If you need those features, you have to look for another solution. Maybe just pick an open source database system.
