### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by KingDuckZ** [peterGraf/pbl#7]
I'm writing a wrap file for meson and it'd be useful to specify a version number in it. However I had a look around and I couldn't find anything, except an old comment in pbl.h stating "revision 1.74". I couldn't find any git tag or anything else. So is the version number 1.74 correct?

**Comment by peterGraf** [comment]
Hello KingDuckZ, I now added the tag v1.5.0. 

I hope that was what you were looking for. 

Btw, before I move the project to github, I had kept the versioning Info here:
https://www.mission-base.com/peter/source/pbl/doc/AIntroduction.html
